version: '3'
services:
    database:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - ${PORT_DATABASE}:3306
    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - ${PORT_MAILCATCHER}:1080
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - ${PORT_PHPMYADMIN}:80
        restart: always
        links:
            - database:db
        depends_on:
            - database
    php:
        build:
            context: ./etc/php
        entrypoint: sh /bin/entrypoint.sh php-fpm
        links:
            - database:mysqldb
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - ./project/:/var/www/html
            - './etc/log/nginx:/var/log/nginx'
            - ./etc/php/entrypoint.sh:/bin/entrypoint.sh
            - '../LaracomCore:/var/www/packages/laracom-core'
    web:
        build: ./etc/nginx
        ports:
            - ${PORT_HTTP}:80
        restart: always
        volumes:
            - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./etc/nginx/app.conf:/etc/nginx/sites-available/application.conf"
            - "./etc/nginx/app.conf:/etc/nginx/sites-enabled/application"
            - "./etc/ssl:/etc/ssl"
            - './etc/log/nginx:/var/log/nginx'
            - ./project/:/var/www/html
        depends_on:
            - php
            - database
